# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'HibridPlayerIOS' #, '0.0.3'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
